
# ============================================================
# Redis mode: specify via program args --app.redis.mode=single
# ============================================================

# --- Redis Single Server ---
app.redis-single.address=redis://127.0.0.1:6379
app.redis-single.password=
app.redis-single.database=0
app.redis-single.connection-minimum-idle-size=4
app.redis-single.connection-pool-size=16

# --- Redis Cluster ---
# app.redis-cluster.node-addresses=redis://127.0.0.1:7001,redis://127.0.0.1:7002,redis://127.0.0.1:7003
# app.redis-cluster.password=
# app.redis-cluster.scan-interval=2000
# app.redis-cluster.master-connection-minimum-idle-size=4
# app.redis-cluster.master-connection-pool-size=16

# --- Redis Sentinel ---
# app.redis-sentinel.master-name=mymaster
# app.redis-sentinel.sentinel-addresses=redis://127.0.0.1:26379,redis://127.0.0.1:26380,redis://127.0.0.1:26381
# app.redis-sentinel.password=
# app.redis-sentinel.sentinel-password=
# app.redis-sentinel.database=0
# app.redis-sentinel.connection-minimum-idle-size=4
# app.redis-sentinel.connection-pool-size=16
