# Primary MongoDB (coupons)
app.mongodb.primary.uri=mongodb://localhost:27017
app.mongodb.primary.database=bitmapDB
app.mongodb.primary.username=mongoadmin
app.mongodb.primary.password=secret
app.mongodb.primary.auth-database=admin

# Secondary MongoDB (e.g. analytics / audit)
#app.mongodb.secondary.uri=mongodb://localhost:27017
#app.mongodb.secondary.database=coupon_platform_secondary